### PR TITLE
Packaging, syslog and bugfixes.

### PR DESCRIPTION
**Pull request by rmedaer**
I would like to use hooktftp server in production for VoIP systems. So I improved you version with following features:
  * Source tree refactoring; just a review of directory tree with std folders.
  * Custom user-agent on HTTP hooks. It provides indication to HTTP server about hooktftp usage.
  * Syslog logging; replace fmt.Print**** by std syslog system.
  * Debian package refactoring; I rewrote Debian packaging :
    * Added default configuration file
    * Added init.d script

### CODE REVIEW

**Comment by rmedaer** [comment]
Note: It breaks travis build and tests because of changes: sources tree, makefiles, ... Although it always run correctly.

**Comment by epeli** [comment]
This looks pretty good. The packaging had a quite a lot cruft. Glad to see it cleaned up. Also the acceptance test were bit fragile which is kinda pain to work with. 

But I see that you listed in the todo: "Rewrite go tests". Why?

**Comment by rmedaer** [comment]
Hi Esa,

> This looks pretty good.

Thank's. 

> Also the acceptance test were bit fragile which is kinda pain to work with.
> But I see that you listed in the todo: "Rewrite go tests". Why?

I just want to split (more than currently) the unit tests and the acceptance tests to looks like ...

  * Unit tests: part of the source code and building procedure.
  * Acceptance (or end-to-end) tests: part of packaging and releasing.

About the end-to-end tests, I'm rewriting them to use 3 kind of files (small, medium & large) with each hooks (shell, file, http).

This pull request is a preview. As I tagged in forked repo, I test it in beta. I should finish tests before the end of this week (depending my calendar).

**Comment by rmedaer** [comment]
Hi,
As promised I'm releasing with following features:

  * Bugfix: Hook shell output buffering to avoid closing stream from cmd.
  * Improvement: Set syslog optionnal / Verbose option to redirect log to stderr.
  * Feature: End-to-end tests rewriting (such as discussed).
  * Bugfix: Fix io.reader in hooks tests.

I also updated GO packages and path. The build procedure and Travis configuration has been changed in same time !

**Pull request merged**
